export { default as Welcome } from './Welcome'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as VerifyOtp } from './VerifyOtp'
export { default as InputEmail } from './InputEmail'
export { default as MainTab } from './MainTab'
export { default as Profile } from './Profile'
